apiVersion: v1
kind: Service
metadata:
  name:  antsy-rtp-service
  namespace: antsy
spec:
  type: NodePort
  selector:
    app: antsy-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000